version: 0.1

phases:
  install:
    commands:
      - echo Nothing to install
  pre_build:
    commands:
      - echo Installing Express and ElasticSearch Dependancies...
      - npm install elasticsearch
      - npm install express
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
     - echo No Post Build
artifacts:
  files:
    - app.js
    - node_modules
    - package.json
  discard-paths: yes